"""
Cross-language validation tests.

These tests verify that the Python QR core produces results matching the
reference values in tests/fixtures/, which were generated by
tests/generate_fixtures.py using numpy (OLS) and statsmodels (GLM) as
independent ground truth.

Prerequisites:
    cd /path/to/voe/python
    python tests/generate_fixtures.py
"""

import math
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

# Locate fixtures relative to this file's location
FIXTURES = Path(__file__).parent / "fixtures"


def _require_fixtures(*names):
    """Skip test if any fixture file is missing."""
    missing = [n for n in names if not (FIXTURES / n).exists()]
    if missing:
        pytest.skip(
            f"Fixture files missing: {missing}. "
            f"Run `python tests/generate_fixtures.py` first."
        )


def _load_data():
    from regsens import LinearSensitivity, GLMSensitivity
    X = pd.read_csv(FIXTURES / "X.csv").values
    y_lin = pd.read_csv(FIXTURES / "y_linear.csv").values.ravel()
    y_bin = pd.read_csv(FIXTURES / "y_binary.csv").values.ravel()
    y_cnt = pd.read_csv(FIXTURES / "y_count.csv").values.ravel()
    vnames = ["x1", "x2", "x3", "x4"]
    return X, y_lin, y_bin, y_cnt, vnames, LinearSensitivity, GLMSensitivity


def _check_coef(ref_row, pkg_row, col, atol):
    ref_val = ref_row[col]
    pkg_val = pkg_row[col] if col in pkg_row.index else float("nan")
    if math.isnan(ref_val):
        assert math.isnan(float(pkg_val)), (
            f"{col}: expected NaN, got {pkg_val}"
        )
    else:
        assert abs(ref_val - float(pkg_val)) < atol, (
            f"{col}: ref={ref_val:.8f}  pkg={pkg_val:.8f}  "
            f"diff={abs(ref_val - float(pkg_val)):.2e}"
        )


# ---------------------------------------------------------------------------
# Linear tests
# ---------------------------------------------------------------------------

class TestLinearVsReference:
    """Python regsens linear results must match the numpy OLS reference."""

    @pytest.fixture(autouse=True)
    def load(self):
        _require_fixtures("X.csv", "y_linear.csv", "refs_linear.csv")
        X, y_lin, _, _, vnames, LinearSensitivity, _ = _load_data()
        sens = LinearSensitivity(X, y_lin, variable_names=vnames, n_jobs=1)
        self.result = sens.fit_all_subsets(return_se=True, return_pvalues=True)
        self.df = self.result.to_dataframe(format="wide").set_index("subset_id")
        self.refs = pd.read_csv(FIXTURES / "refs_linear.csv").set_index("subset_id")

    def test_correct_number_of_subsets(self):
        assert len(self.df) == 16

    def test_intercept_coef_all_subsets(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            _check_coef(ref_row, pkg_row, "coef_(Intercept)", atol=1e-8)

    @pytest.mark.parametrize("vname", ["x1", "x2", "x3", "x4"])
    def test_variable_coef_all_subsets(self, vname):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            _check_coef(ref_row, pkg_row, f"coef_{vname}", atol=1e-8)

    def test_rss_all_subsets(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            assert abs(ref_row["rss"] - pkg_row["rss"]) < 1e-8, (
                f"subset_id={sid}: rss ref={ref_row['rss']:.6f}  "
                f"pkg={pkg_row['rss']:.6f}"
            )

    def test_r2_all_subsets(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            ref_r2 = ref_row["r2"]
            pkg_r2 = pkg_row["r2"]
            if math.isnan(ref_r2):
                assert math.isnan(float(pkg_r2))
            else:
                assert abs(ref_r2 - float(pkg_r2)) < 1e-8, (
                    f"subset_id={sid}: r2 diff={abs(ref_r2 - float(pkg_r2)):.2e}"
                )

    def test_aic_all_subsets(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            assert abs(ref_row["aic"] - pkg_row["aic"]) < 1e-6, (
                f"subset_id={sid}: aic diff={abs(ref_row['aic'] - pkg_row['aic']):.2e}"
            )

    @pytest.mark.parametrize("vname", ["(Intercept)", "x1", "x2", "x3", "x4"])
    def test_se_all_subsets(self, vname):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            _check_coef(ref_row, pkg_row, f"se_{vname}", atol=1e-8)

    def test_n_active_correct(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            assert ref_row["n_active"] == pkg_row["n_vars"]


# ---------------------------------------------------------------------------
# Binomial GLM tests
# ---------------------------------------------------------------------------

class TestBinomialVsReference:
    """Python regsens binomial results must match the statsmodels reference."""

    @pytest.fixture(autouse=True)
    def load(self):
        _require_fixtures("X.csv", "y_binary.csv", "refs_binomial.csv")
        X, _, y_bin, _, vnames, _, GLMSensitivity = _load_data()
        sens = GLMSensitivity(
            X, y_bin, family="binomial",
            variable_names=vnames, n_jobs=1, warm_start=False,
        )
        self.result = sens.fit_all_subsets()
        self.df = self.result.to_dataframe(format="wide").set_index("subset_id")
        self.refs = pd.read_csv(FIXTURES / "refs_binomial.csv").set_index("subset_id")

    def test_correct_number_of_subsets(self):
        assert len(self.df) == 16

    def test_intercept_coef_all_subsets(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            _check_coef(ref_row, pkg_row, "coef_(Intercept)", atol=1e-5)

    @pytest.mark.parametrize("vname", ["x1", "x2", "x3", "x4"])
    def test_variable_coef_all_subsets(self, vname):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            _check_coef(ref_row, pkg_row, f"coef_{vname}", atol=1e-5)

    def test_deviance_all_subsets(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            assert abs(ref_row["deviance"] - pkg_row["deviance"]) < 1e-5, (
                f"subset_id={sid}: deviance diff="
                f"{abs(ref_row['deviance'] - pkg_row['deviance']):.2e}"
            )

    def test_aic_all_subsets(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            assert abs(ref_row["aic"] - pkg_row["aic"]) < 0.01, (
                f"subset_id={sid}: aic diff={abs(ref_row['aic'] - pkg_row['aic']):.4f}"
            )


# ---------------------------------------------------------------------------
# Poisson GLM tests
# ---------------------------------------------------------------------------

class TestPoissonVsReference:
    """Python regsens Poisson results must match the statsmodels reference."""

    @pytest.fixture(autouse=True)
    def load(self):
        _require_fixtures("X.csv", "y_count.csv", "refs_poisson.csv")
        X, _, _, y_cnt, vnames, _, GLMSensitivity = _load_data()
        sens = GLMSensitivity(
            X, y_cnt, family="poisson",
            variable_names=vnames, n_jobs=1, warm_start=False,
        )
        self.result = sens.fit_all_subsets()
        self.df = self.result.to_dataframe(format="wide").set_index("subset_id")
        self.refs = pd.read_csv(FIXTURES / "refs_poisson.csv").set_index("subset_id")

    def test_correct_number_of_subsets(self):
        assert len(self.df) == 16

    def test_intercept_coef_all_subsets(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            _check_coef(ref_row, pkg_row, "coef_(Intercept)", atol=1e-5)

    @pytest.mark.parametrize("vname", ["x1", "x2", "x3", "x4"])
    def test_variable_coef_all_subsets(self, vname):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            _check_coef(ref_row, pkg_row, f"coef_{vname}", atol=1e-5)

    def test_deviance_all_subsets(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            assert abs(ref_row["deviance"] - pkg_row["deviance"]) < 1e-5, (
                f"subset_id={sid}: deviance diff="
                f"{abs(ref_row['deviance'] - pkg_row['deviance']):.2e}"
            )

    def test_aic_all_subsets(self):
        for sid, ref_row in self.refs.iterrows():
            pkg_row = self.df.loc[sid]
            assert abs(ref_row["aic"] - pkg_row["aic"]) < 0.01, (
                f"subset_id={sid}: aic diff={abs(ref_row['aic'] - pkg_row['aic']):.4f}"
            )
